// Placeholder for file generated by Cascade

module program_logic(
	input wire clk,
	input wire reset,
	
	input wire         softreg_req_valid,
	input wire         softreg_req_isWrite,
	input wire[31:0]   softreg_req_addr,
	input wire[63:0]   softreg_req_data,
	
	output wire        softreg_resp_valid,
	output wire[63:0]  softreg_resp_data
);

parameter app_num = 0;

endmodule
